# This file was generated by GoReleaser. DO NOT EDIT.
cask "subcor" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "d6cb1ff700218df8fa0409a96c8668da166a7013f6fc07fd8ba81feb91440cfe"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "65dbd6cf0a3a8317c2e4c231baa8e1cc1e521360d86cb7694185bf44f4a150c5"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end
  on_linux do
    on_arm do
      sha256 "2887ec024f57422029394eb2f106c8cf258c915fec4d8d763aea820fe4fb22d9"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "23e4e3cab16b125bc854c76037e6f96b35ef54e96805e0326741ff30e5169c09"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end

  name "subcor"
  desc "Command-line interface for Subcor"
  homepage "https://get.subcor.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subcor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/subcor"]
    end
  end

  # No zap stanza required
end
