# This file was generated by GoReleaser. DO NOT EDIT.
cask "subcor" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a31db67b2a4575d2a89f23cc874a35e6813357f6517130e6389b9f0b089ef27a"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "23c5419303bbf0c8a957e95e7ac88b03c51a82a8f2ee731f9ca52d6195a89f06"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end
  on_linux do
    on_arm do
      sha256 "c3696de2a9cd166f1feb311a1c82436c7a56df0b1c7f59256e882bf4ba2c07db"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "591eb3746cad5fe770577e5fd3b72eb60d2ebb2038fae2a5cf67649bb488a219"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end

  name "subcor"
  desc "Command-line interface for Subcor"
  homepage "https://get.subcor.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subcor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/subcor"]
    end
  end

  # No zap stanza required
end
