# This file was generated by GoReleaser. DO NOT EDIT.
cask "subcor" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "c4bd54145a9df3582d7310a7ad2d870d100a6cb8e1fe463c78ba44fc78b3f722"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "ecf65d9363c8abfcdfc3c751b5b20dca8ca3b9657fdbb25fb7518550468b7b5d"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_darwin_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end
  on_linux do
    on_arm do
      sha256 "db4e103197de5f4d74980c99f0ae11c59aaa5bbe6c47d404938acbb428f045bc"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_arm64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
    on_intel do
      sha256 "576012af52a5395a125836f209d918568b62b22e5e3657e65d3391e858f4eb24"
      url "https://github.com/subcor-ai/get.subcor.ai/releases/download/v#{version}/subcor_linux_amd64.tar.gz",
        verified: "github.com/subcor-ai/get.subcor.ai/"
    end
  end

  name "subcor"
  desc "Command-line interface for Subcor"
  homepage "https://get.subcor.ai/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "subcor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/subcor"]
    end
  end

  # No zap stanza required
end
